### ISSUE TITLE
Asset Extraction

### ISSUE THREAD

**Issue by ACG-YAO** [chungmin99/garfield#11]
How to do asset extraction like this in the demo?
[drop.webm](https://github.com/chungmin99/garfield/assets/147377345/ebae5192-bd6d-41c1-b898-0b646eb0c8f2)

**Comment by WMXwmxwalter** [comment]
Hi, you can extract the selected gaussian center points, incorporate them into the mesh, and then input this mesh into software like Blender for simulation. Subsequently, render the animation in nerfstudio, using the same transformation matrix. Additionally, you can render the background and shadow separately in Blender; take [this](https://docs.nerf.studio/extensions/blender_addon.html) as a reference.

**Comment by ACG-YAO** [comment]
Thanks for your quick reply! Could you please guide me on how to extract the chosen Gaussian center points and integrate them into the mesh?

**Comment by WMXwmxwalter** [comment]
I use [meshlab](https://www.meshlab.net/) for mesh reconstruction, but using poisson mesh extraction , similar to what nerfstudio offers, is also ok.
