### ISSUE TITLE
Same random number for both mask sampling and scale densification

### ISSUE THREAD

**Issue by lxxue** [chungmin99/garfield#13]
Hi, thank you for the awesome work and the well-documented code. I am really impressed by the design and the amazing grouping quality.

I have a small question regarding the `next_group` function:
https://github.com/chungmin99/garfield/blob/efd4490d772a5d3644251f46c22f4a7aa75c1309/garfield/garfield_datamanager.py#L265-L307

Here the same random number is used in `line 274-278` for inverse CDF sampling and `line 290-307` for scale densification. Then only a fraction of the scale range is sampled during training for a specific mask. For example, let's say one pixel has a mask CDF of `[0.2, 0.5, 1.0]`. The smallest mask with scale `s0` will be selected when a random number `p < 0.2` is generated. Then for training with this mask, only scale `p*s0 < 0.2s0` will be used.

I wonder if I misunderstood something or if this is intended?

**Comment by chungmin99** [comment]
First, thank you, and really appreciate the close eye on the code :) 

> ... Then for training with this mask, only scale p*s0 < 0.2s0 will be used.

This wasn't intended... and empirically, there seems to be no difference from using two different sets of random vectors. This should be addressed in #14, and I will close the issue once the PR is merged.

**Comment by kerrj** [comment]
#14 closes this
