### ISSUE TITLE
About the local usage of garfield

### ISSUE THREAD

**Issue by MADONOKOUKI** [chungmin99/garfield#17]
Hi, I want to use garfield locally without using NeRF studio.

It aimed at obtaining the final segmentation result local (like assume to use on server).

Can we do this by this code?

**Comment by chungmin99** [comment]
This codebase requires nerfstudio to be installed -- it heavily relies on this framework for all the training/rendering. 

It follows the guidelines from https://docs.nerf.studio/developer_guides/new_methods.html.
