### ISSUE TITLE
Suggestions for reducing vram usage

### ISSUE THREAD

**Issue by CameronFraser** [chungmin99/garfield#18]
Hi,

Is there any suggestion for how to reduce gpu memory usage? I've been attempting to try this with custom data but I run out of gpu memory during the mask generation. I have an rtx a5000 (24 gb vram).

Thanks!

**Comment by chungmin99** [comment]
Hmm, I'm also running with 4090, which has 24 GB VRAM.

Is it possible that you're running out of memory (on RAM)? I personally found that keeping all the masks in memory (even on CPU) can get very memory intensive, and the current codebase has difficulty handling more than ~400 images. This is something I was hoping to fix, but haven't gotten around to. :/

**Comment by CameronFraser** [comment]
@chungmin99 my bad, the images were very large which was causing issues, fixed it with a minor downscale
