### ISSUE TITLE
Pre-trained models on LERF dataset

### ISSUE THREAD

**Issue by weijielyu** [chungmin99/garfield#22]
Thanks for this exciting work. I wonder if you could release pre-trained models on LERF dataset, or just the rendered segmentations?

**Comment by chungmin99** [comment]
Hi! Thanks for your interest in this project :)

> I wonder if you could release pre-trained models on LERF dataset, or just the rendered segmentations?

The results should be reproducible with the current codebase -- on a 4090, it takes around ~30 minutes to optimize GARField for a given scene (~5-10 min to generate the SAM masks for the training images, and ~15 min for 30k steps). 

At the moment, I'm not sure if there exists a standard on releasing nerfstudio models. It's an actively changing codebase, which could break compatibility with past checkpoints. If you have any suggestions on this front, let us know. 

Also, not really sure about what you mean about "the rendered segmentations" -- the segmentation/grouping can vary a lot per scale.

**Comment by weijielyu** [comment]
I appreciate the information you provide! Thanks again for this great work!
