### ISSUE TITLE
inf Loss

### ISSUE THREAD

**Issue by yhyang-myron** [chungmin99/garfield#24]
Hi, Thanks for your excellent work!
When I trained on my own dataset, I met the inf loss problem. In several steps starting from 2000 steps, instance_loss_4 and total_loss are inf. After training for a few steps, Loss returned to normal. Is this a normal phenomenon?
Looking forward to your reply, Thank you!

**Comment by chungmin99** [comment]
Oh, this is interesting! I've never actually monitored the loss... I'm glad it worked out in the end. 

My hunch is that the affinity features are initialized to similar values, so `nansum()` gets an unexpected high value at the beginning. Then, as the pulling forces re-organize the features (`instance_loss_1`, `instance_loss_2`), the pushing loss stabilizes. 

https://github.com/chungmin99/garfield/blob/d422542077e149cdd7a90214fd100051d4920e1f/garfield/garfield_model.py#L236-L240
