### ISSUE TITLE
failed for ''Running GARField with Gaussian Splatting geometry!''

### ISSUE THREAD

**Issue by xiyufeng2** [chungmin99/garfield#25]
The previous process in secceed for ''Running GARField''. But sth. went wrong when I use the command ''ns-train garfield-gauss --data /your/data/here --pipeline.garfield-ckpt outputs/y/.../config.yml''. Error is as following:

[5/5] c++ bindings.cuda.o backward.cuda.o forward.cuda.o ext.o -shared -L/home/moonlight/.conda/envs/nerfstudio/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/moonlight/.conda/envs/nerfstudio/lib64 -lcudart -o gsplat_cuda.so
FAILED: gsplat_cuda.so 
c++ bindings.cuda.o backward.cuda.o forward.cuda.o ext.o -shared -L/home/moonlight/.conda/envs/nerfstudio/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/moonlight/.conda/envs/nerfstudio/lib64 -lcudart -o gsplat_cuda.so
/usr/bin/ld: cannot find -lcudart: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

can you afford some help?thank you

**Comment by chungmin99** [comment]
Hi, this appears to be an issue with your `gsplat` installation, or an issue with Nerfstudio's Gaussian Splat.

Does `ns-train splatfacto ...` work for you? Otherwise, I would try reinstalling the `gsplat` package, perhaps from the GitHub repo.

**Comment by barney2074** [comment]
Hello

Adding to this thread, similar issue but different error

When I try to run GARField with Gaussian Splatting, I get the following error:
`RuntimeError: Optimizer config for 'xyz' not found in config file. Make sure you specify an optimizer for each parameter group. Provided configs were: dict_keys(['means', 'features_dc', 'features_rest', 'opacities', 'scales', 'quats', 'camera_opt'])
`
To answer the question above, yes `ns-train splatfacto` works for me

Just to check I've got the arguments right, my command is:
`ns-train garfield-gauss --data <path to original data used for gaussian splat training> --pipeline.garfield-ckpt <path to config.yml from gaussian splat training>`

thanks in advance

**Comment by chungmin99** [comment]
Hi, the parameter name mismatch issue is due to the recent splatfacto rename PR in nerfstudio (https://github.com/nerfstudio-project/nerfstudio/pull/2946), which this repo addresses in https://github.com/chungmin99/garfield/pull/23. This issue is related to https://github.com/chungmin99/garfield/issues/26. 

 `garfield-gauss` should work if you pull the latest version of nerfstudio.

**Comment by barney2074** [comment]
Hi

Many thanks for the reply
I did look through the other issues, but missed that one

Andrew
