### ISSUE TITLE
Question about demonstration

### ISSUE THREAD

**Issue by sp9103** [chungmin99/garfield#3]
Hi, Thank you for sharing your amazing project :)

1. Can I check the training results using the viewer after training is finished? If I finish training and quit nerf-studio, is there a way to return to the last state of training?
2. It looks like mesh extraction was performed in the asset extraction of the project page. How can I extract the mesh?

**Comment by chungmin99** [comment]
> Can I check the training results using the viewer after training is finished? If I finish training and quit nerf-studio, is there a way to return to the last state of training?
You can use `ns-viewer` to view your previous runs, as long as you have your previous config files + checkpoints! This is also the path you use for training `garfield-gauss`. 

> It looks like mesh extraction was performed in the asset extraction of the project page. How can I extract the mesh?
I believe you should be able to use `garfield-gauss` -- crop the object you want, then export it? I'm currently not sure if splatfacto supports mesh extraction. Let me know if you run into any issues.

**Comment by sp9103** [comment]
Thank you for your fast response. I will check it, and if there are no issues, I'll close this issue.
