### ISSUE TITLE
'tcnn' is not defined while tiny-cuda-nn has been installed and cmaked

### ISSUE THREAD

**Issue by zw20130717** [chungmin99/garfield#34]
![2024-06-14 18-49-17 的屏幕截图](https://github.com/chungmin99/garfield/assets/166890502/08ec0935-488c-4845-8c94-1cda3d5a47d0)
Hi, dear author, thanks for your amazing work. I have run the nerfstudio project successfully before. But this time when I installed garfield and tried to run 'ns-train garfield', I was informed 'tcnn is not defined'. I tried reinstalling or upgrading torch, python, cuda toolkit and tiny-cuda-nn but it didnt help, and now i cant even run 'ns-train nerfacto'. Any idea how to solve this problem? I'd very much appreciate it.

**Comment by deepgoyal19** [comment]
HI! Try this command- `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
